const String login ='http://localhost:8000/tiempo/api/login';
const String crear_servicio='http://127.0.0.1:8000/tiempo/api/servicios';
const String crear_usuario='http://localhost:8000/tiempo/api/usuarios';
const String crear_cuenta ='http://localhost:8000/tiempo/api/cuentas';
const String crear_rols='http://localhost:8000/tiempo/api/rols';
const String crear_categoria='http://localhost:8000/tiempo/api/categorias';
const String crear_intereses ='http://localhost:8000/tiempo/api/intereses';
const String crear_calificaciones='http://127.0.0.1:8000/tiempo/api/calificaciones';
const String crear_transacciones='http://127.0.0.1:8000/tiempo/api/transacciones';
